services:
  joke-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: joke-bot:local
    env_file: .env
    container_name: joke-bot
    restart: unless-stopped
    volumes:
      - ./log:/app/log
